name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/moja-aplikacja:latest .

    - name: Push Docker image to ACR
      run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/moja-aplikacja:latest
